# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import time
import psutil

from config import CHECK_INTERVAL
from telegram_alert import send_telegram_alert


class PowerMonitor:
    """
    Monitors laptop charging status.
    If the charger is disconnected, it triggers callback + Telegram alert.
    """

    def __init__(self, on_disconnect_callback):
        self.on_disconnect_callback = on_disconnect_callback
        self.last_state = None
        self.running = False

    def get_power_status(self):
        """
        Returns:
            True  -> plugged in
            False -> unplugged
            None  -> battery info unavailable
        """
        battery = psutil.sensors_battery()
        if battery is None:
            return None
        return battery.power_plugged

    def check_once(self):
        current_state = self.get_power_status()

        if current_state is None:
            return

        if self.last_state is None:
            self.last_state = current_state
            return

        if self.last_state is True and current_state is False:
            self.on_disconnect_callback()
            send_telegram_alert(
                "⚠️ LaptopGuard Alert\nThe charger was disconnected from the laptop."
            )

        self.last_state = current_state

    def start(self):
        self.running = True
        while self.running:
            self.check_once()
            time.sleep(CHECK_INTERVAL)

    def stop(self):
        self.running = False