# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import requests
from config import BOT_TOKEN, CHAT_ID


def send_telegram_alert(message: str) -> bool:
    """
    Sends a Telegram message using the configured bot token and chat ID.
    Returns True if successful, otherwise False.
    """
    if BOT_TOKEN == "YOUR_TELEGRAM_BOT_TOKEN" or CHAT_ID == "YOUR_CHAT_ID":
        print("Telegram configuration is not set.")
        return False

    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": message,
    }

    try:
        response = requests.post(url, data=payload, timeout=10)
        return response.status_code == 200
    except requests.RequestException as exc:
        print(f"Telegram request failed: {exc}")
        return False