# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import threading
import customtkinter as ctk
from plyer import notification

from config import APP_TITLE, WINDOW_SIZE
from monitor import PowerMonitor

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")


class LaptopGuardApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.title(APP_TITLE)
        self.geometry(WINDOW_SIZE)
        self.resizable(False, False)

        self.monitor = None
        self.monitor_thread = None

        self._build_ui()

    def _build_ui(self):
        self.grid_columnconfigure(0, weight=1)

        self.title_label = ctk.CTkLabel(
            self,
            text="LaptopGuard",
            font=ctk.CTkFont(size=28, weight="bold")
        )
        self.title_label.pack(pady=(30, 8))

        self.subtitle_label = ctk.CTkLabel(
            self,
            text="Laptop Charger Security Monitor",
            font=ctk.CTkFont(size=14)
        )
        self.subtitle_label.pack(pady=(0, 20))

        self.status_label = ctk.CTkLabel(
            self,
            text="Status: Idle",
            font=ctk.CTkFont(size=15)
        )
        self.status_label.pack(pady=(0, 20))

        self.start_button = ctk.CTkButton(
            self,
            text="Start Monitoring",
            width=180,
            height=40,
            command=self.start_monitoring
        )
        self.start_button.pack(pady=8)

        self.stop_button = ctk.CTkButton(
            self,
            text="Stop Monitoring",
            width=180,
            height=40,
            command=self.stop_monitoring,
            fg_color="#444444",
            hover_color="#333333"
        )
        self.stop_button.pack(pady=8)

        self.info_box = ctk.CTkTextbox(
            self,
            width=420,
            height=80
        )
        self.info_box.pack(pady=(20, 20))
        self.info_box.insert(
            "1.0",
            "This application monitors your laptop's charging state.\n"
            "If the charger is unplugged, it triggers a desktop notification\n"
            "and sends a Telegram alert."
        )
        self.info_box.configure(state="disabled")

    def show_disconnect_alert(self):
        self.status_label.configure(text="Status: Charger disconnected!")

        notification.notify(
            title="LaptopGuard Alert",
            message="The charger was disconnected from the laptop.",
            timeout=5
        )

    def start_monitoring(self):
        if self.monitor is not None and self.monitor.running:
            self.status_label.configure(text="Status: Monitoring already active")
            return

        self.monitor = PowerMonitor(self.show_disconnect_alert)
        self.monitor_thread = threading.Thread(target=self.monitor.start, daemon=True)
        self.monitor_thread.start()

        self.status_label.configure(text="Status: Monitoring active")

    def stop_monitoring(self):
        if self.monitor is not None:
            self.monitor.stop()
            self.status_label.configure(text="Status: Monitoring stopped")

    def on_close(self):
        if self.monitor is not None:
            self.monitor.stop()
        self.destroy()